// Copyright (c) 2024-2025 Accenture, All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//         http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Description:
// Jenkins pipeline to create Google Compute Engine (GCE) instance templates
// for use with CVD Launcher and CTS Execution jobs.
//
// It reuses the AAOS Docker Builder Docker image, which contains all the
// necessary packages to create the instance template.
pipeline {

  // Parameters defined in groovy/job.groovy
  agent {
    kubernetes {
      yaml """\
        apiVersion: v1
        kind: Pod
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          labels:
            aaos_pod: "true"
        spec:
          tolerations:
          - key: workloadType
            operator: Equal
            value: android
            effect: "NoSchedule"
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: aaos_pod
                    operator: Exists
                topologyKey: kubernetes.io/hostname
          hostname: jenkins-aaos-cf-build-pod
          serviceAccountName: ${JENKINS_SERVICE_ACCOUNT}
          containers:
          - name: builder
            image: ${CLOUD_REGION}-docker.pkg.dev/${CLOUD_PROJECT}/${ANDROID_BUILD_DOCKER_ARTIFACT_PATH_NAME}:latest
            imagePullPolicy: Always
            command:
            - sleep
            args:
            - 5h
            resources:
              limits:
                cpu: 98000m
                memory: 180000Mi
              requests:
                cpu: 98000m
                memory: 180000Mi
          nodeSelector:
            workloadLabel: android
      """.stripIndent()
    }
  }

  stages {
    stage ('Stage 1: Create base instance template') {
      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          script {
            env.MACHINE_TYPE_DESCRIPTION=''
            if ( "${env.MACHINE_TYPE}" != "" ) {
              env.MACHINE_TYPE_DESCRIPTION="${env.MACHINE_TYPE}"
            } else {
              env.MACHINE_TYPE_DESCRIPTION="${env.CUSTOM_VM_TYPE}-custom-${env.CUSTOM_CPU}"
            }
            currentBuild.description = "Revision: ${env.ANDROID_CUTTLEFISH_REVISION}" + "<br/>" + "Prebuilt: ${env.ANDROID_CUTTLEFISH_PREBUILT}" + "<br/>" + "${env.MACHINE_TYPE_DESCRIPTION}" + "<br/>" + "$BUILD_USER"
          }
          sh '''
            ADDITIONAL_NETWORKING="${ADDITIONAL_NETWORKING}" \
            BOOT_DISK_SIZE="${BOOT_DISK_SIZE}" \
            BOOT_DISK_TYPE="${BOOT_DISK_TYPE}" \
            CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            MACHINE_TYPE="${MACHINE_TYPE}" \
            CUSTOM_VM_TYPE="${CUSTOM_VM_TYPE}" \
            CUSTOM_CPU="${CUSTOM_CPU}" \
            CUSTOM_MEMORY="${CUSTOM_MEMORY}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
            VM_INSTANCE_CREATE="${VM_INSTANCE_CREATE}" \
            SUBNET=${SUBNET} \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 1
          '''
        }
      }
    }

    stage ('Stage 2: Create base VM instance') {

      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          sh '''
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
            VM_INSTANCE_CREATE="${VM_INSTANCE_CREATE}" \
            MAX_RUN_DURATION="${MAX_RUN_DURATION}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            SUBNET=${SUBNET} \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 2
          '''
        }
      }
    }

    stage ('Stage 3: Install Cuttlefish on base VM instance') {

      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          maskPasswords(varPasswordPairs: [[var: 'REPO_PASSWORD']], varMaskRegexes: []) {
            sh '''
              ADDITIONAL_NETWORKING="${ADDITIONAL_NETWORKING}" \
              ANDROID_CUTTLEFISH_PREBUILT="${ANDROID_CUTTLEFISH_PREBUILT}" \
              CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
              CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
              CUTTLEFISH_URL="${ANDROID_CUTTLEFISH_REPO_URL}" \
              REPO_USERNAME="${REPO_USERNAME}" \
              REPO_PASSWORD="${REPO_PASSWORD}" \
              CURL_UPDATE_COMMAND=\""${CURL_UPDATE_COMMAND}"\" \
              JAVA_VERSION="${JAVA_VERSION}" \
              NODEJS_VERSION="${NODEJS_VERSION}" \
              PROJECT=${CLOUD_PROJECT} \
              REGION=${REGION:-${CLOUD_REGION}} \
              SUBNET=${SUBNET} \
              VM_INSTANCE_CREATE="${VM_INSTANCE_CREATE}" \
              ZONE=${ZONE:-${CLOUD_ZONE}} \
              ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 3
            '''
          }
          archiveArtifacts artifacts: 'android*.txt', followSymlinks: false, onlyIfSuccessful: false, allowEmptyArchive: true
        }
      }
    }

    stage ('Stage 4: Setup SSH access on base VM instance') {

      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          sh '''
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
            VM_INSTANCE_CREATE="${VM_INSTANCE_CREATE}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            SUBNET=${SUBNET} \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 4
          '''
        }
      }
    }

    stage ('Stage 5: Create Cuttlefish instance template from VM instance') {

      when {
        allOf {
          expression { env.DELETE == 'false' }
          expression { env.ANDROID_CUTTLEFISH_REVISION }
        }
      }

      steps {
        container(name: 'builder') {
          sh '''
            BOOT_DISK_TYPE="${BOOT_DISK_TYPE}" \
            CUTTLEFISH_POST_COMMAND="${ANDROID_CUTTLEFISH_POST_COMMAND}" \
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            VM_INSTANCE_CREATE="${VM_INSTANCE_CREATE}" \
            MACHINE_TYPE="${MACHINE_TYPE}" \
            CUSTOM_VM_TYPE="${CUSTOM_VM_TYPE}" \
            CUSTOM_CPU="${CUSTOM_CPU}" \
            CUSTOM_MEMORY="${CUSTOM_MEMORY}" \
            OS_PROJECT="${OS_PROJECT}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            SUBNET=${SUBNET} \
            CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 5
          '''
        }
      }
    }

    stage ('Stage 6: Delete all artifacts') {

      when {
        allOf {
          expression { env.DELETE == 'true' }
          expression { env.ANDROID_CUTTLEFISH_REVISION || env.CUTTLEFISH_INSTANCE_NAME }
        }
      }

      steps {
        container(name: 'builder') {
          sh '''
            CUTTLEFISH_REVISION="${ANDROID_CUTTLEFISH_REVISION}" \
            PROJECT=${CLOUD_PROJECT} \
            REGION=${REGION:-${CLOUD_REGION}} \
            CUTTLEFISH_INSTANCE_NAME="${CUTTLEFISH_INSTANCE_NAME}" \
            SUBNET=${SUBNET} \
            ZONE=${ZONE:-${CLOUD_ZONE}} \
            ./workloads/android/pipelines/environment/cf_instance_template/cf_create_instance_template.sh 6
          '''
        }
      }
    }
  }
}
