# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    iam.gke.io/gcp-service-account: gke-{{ .Values.config.namespacePrefix }}keycloak-sa@{{ .Values.config.projectID }}.iam.gserviceaccount.com
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-creds
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-horizon-admin
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "horizon-admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-gerrit-admin
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "gerrit-admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-jenkins-admin
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "jenkins-admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-grafana-admin
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "admin"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-initial-creds
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  labels:
    jenkins.io/credentials-type: "usernamePassword"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "dbusername"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-mcp-gateway-registry-admin
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  username: "mcp-gateway-registry-admin"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: keycloak-secret-store
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.config.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.config.region }}
          clusterName: sdv-cluster
          serviceAccountRef:
            name: keycloak-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-initial-creds
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}keycloak-admin-password-b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-horizon-admin-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-horizon-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}keycloak-horizon-admin-password-b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gerrit-admin-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-gerrit-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}gerrit-admin-password-b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-admin-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-jenkins-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}jenkins-admin-password-b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-grafana-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}grafana-admin-password-b64
        decodingStrategy: Base64

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-admin-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: postgresql-initial-creds
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}postgres-admin-password-b64
        decodingStrategy: Base64
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mcp-gateway-registry-admin-initial-secret
  namespace: {{ .Values.config.namespacePrefix }}keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 10s
  secretStoreRef:
    kind: SecretStore
    name: keycloak-secret-store
  target:
    name: keycloak-mcp-gateway-registry-admin
    creationPolicy: Merge
  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.config.namespacePrefix }}mcp-gateway-registry-admin-password-b64
        decodingStrategy: Base64
