# Copyright (c) 2024-2026 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.config.namespacePrefix }}monitoring-tools
  namespace: {{ .Values.config.namespacePrefix }}argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.config.namespacePrefix }}horizon-sdv
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: gitops/apps/monitoring-tools
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        config:
          projectID: {{ .Values.config.projectID }}
          namespacePrefix: {{ .Values.config.namespacePrefix }}
          isSubEnvironment: {{ .Values.config.isSubEnvironment }}
        spec:
          source:
            repoURL: {{ .Values.spec.source.repoURL }}
            targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.config.namespacePrefix }}monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Allow Prometheus to be scraped by Grafana
{{- if .Values.config.enableNetworkPolicies }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-ingress-from-grafana
  namespace: {{ .Values.config.namespacePrefix }}monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: grafana
    ports:
    - protocol: TCP
      port: 9090   # Prometheus API

{{- end }}
