# Copyright (c) 2024-2025 Accenture, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Description:
# Storage classes used for Jenkins build caches.
# Prefix reclaimable-storage-class is referenced in System Variables so
# jobs may choose the correct storage class based on Android version and
# target.

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-14
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-14-rpi
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-15
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-15-rpi
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-abfs
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-16
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.config.namespacePrefix }}reclaimable-storage-class-android-16-rpi
  annotations:
    reclaimable-pv-releaser.kubernetes.io/controller-id: dynamic-reclaimable-pvc-controllers
    argocd.argoproj.io/sync-wave: "3"
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
